---
title: "KI Labs - Take home code challenge"
subtitle: "Build an interview calendar API"
author: Barbara Borges Ribeiro
output: html_document
---

```{r}
source("Calendar.R")
```


USAGE EXAMPLE

```{r}
cal <- Calendar$new()

# The interviewer Ines is available all of next week 
# (22 to 26 October 2018), starting at 9am and 
# finishing at 4pm
cal$registerInterviewer("Ines")
cal$setSlot(role = "interviewer", name = "Ines",
  list("2018-10-22", "2018-10-23", "2018-10-24", "2018-10-25", "2018-10-26"),
  list(9:15, 9:15, 9:15, 9:15, 9:15)
)

# The interviewer Ingrid is available from 12pm to 6pm
# on Mon/Wed and from 9am to 12pm on Tues/Thurs
cal$registerInterviewer("Ingrid")
cal$setSlot(role = "interviewer", name = "Ingrid",
  list("2018-10-22", "2018-10-23", "2018-10-24", "2018-10-25"),
  list(12:17, 9:11, 12:17, 9:11)
)

# The candidate Carl is available at 9 am any weekday,
# and until noon on Wednesday
cal$registerCandidate("Carl")
cal$setSlot(role = "candidate", name = "Carl",
  list("2018-10-22", "2018-10-23", "2018-10-24", "2018-10-25", "2018-10-26"),
  list(9, 9, 9:11, 9, 9)
)

cal$searchAvailability("Carl")
cal$searchAvailability("Carl", "Ines")
cal$searchAvailability("Carl", "Ingrid")
cal$searchAvailability("Carl", "Ines", "Ingrid")

```